// Generated by scripts/build-log-catalog.ts.
import type { LogSiteCatalog } from "@snoai/utils";
export const logSiteCatalog: LogSiteCatalog = {
	"build_id": "f326c1dfa3fc43466fbc7a55c3d62ad0c3986ff6f9c1a2fcf98f31d82e2ed02a",
	"sites": {
		"installer.observe.bootstrap.skipped": {
			"file": "apps/mem-claw/bin/_observe-onboarding.js",
			"function": "bootstrapObserveInstall",
			"line": 117,
			"column": 19,
			"file_hash": "6ddd47a48e9719bca34d9f92fd7bb9f2e7bd6d4afbc9b28cc19e60ea5c20fd54"
		},
		"installer.observe.shutdown.failed": {
			"file": "apps/mem-claw/bin/_observe-onboarding.js",
			"function": "bootstrapObserveInstall",
			"line": 125,
			"column": 20,
			"file_hash": "6ddd47a48e9719bca34d9f92fd7bb9f2e7bd6d4afbc9b28cc19e60ea5c20fd54"
		},
		"installer.manifest_read_failed": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "loadKConstants",
			"line": 87,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.manifest_default_invalid": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "loadKConstants",
			"line": 93,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.manifest_help_missing": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "loadKConstants",
			"line": 97,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.manifest_lean_hint_missing": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "loadKConstants",
			"line": 101,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.manifest_lean_count_invalid": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "loadKConstants",
			"line": 105,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.arguments_invalid": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "parseArgs",
			"line": 114,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.openclaw_unavailable": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "checkOpenclawOnPath",
			"line": 160,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.openclaw_spawn_failed": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "ocSpawn",
			"line": 179,
			"column": 15,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.observe.skipped": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "runObserveOnboarding",
			"line": 215,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.config_invalid_before_install": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "main",
			"line": 546,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.openclaw_install_failed": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "main",
			"line": 575,
			"column": 4,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.config_invalid_after_install": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "main",
			"line": 584,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.config_write_failed": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "main",
			"line": 674,
			"column": 3,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"installer.unhandled_failure": {
			"file": "apps/mem-claw/bin/mem-claw-install.js",
			"function": "<anonymous callback>",
			"line": 687,
			"column": 2,
			"file_hash": "fe625ce5baa6472eb2ea03e79a982f9a17198454ea266eaf3392b7809599d6c5"
		},
		"memdump.command.failed": {
			"file": "apps/mem-claw/bin/sno-memdump.js",
			"function": "<module>",
			"line": 7,
			"column": 2,
			"file_hash": "be6452ce54d6db519bd8608dfb03c2c9ffc9b5f147c352a88aa5fc42c2c70609"
		},
		"operations.learning-file-hooks.setupSelfImprovement.6219afe5d1": {
			"file": "apps/mem-claw/src/hooks/learning-file-hooks.ts",
			"function": "setupSelfImprovement",
			"line": 97,
			"column": 5,
			"file_hash": "d2474e4d8ea7d91a1611b38a8d6fdb3cb24d5cd6d8815c1fa8600d3ed8036f72"
		},
		"operations.learning-file-hooks.appendSelfImprovementNote.f55023edef": {
			"file": "apps/mem-claw/src/hooks/learning-file-hooks.ts",
			"function": "appendSelfImprovementNote",
			"line": 124,
			"column": 5,
			"file_hash": "d2474e4d8ea7d91a1611b38a8d6fdb3cb24d5cd6d8815c1fa8600d3ed8036f72"
		},
		"plugin.openclaw-observe-controller.finalizeObserveSession.8cc8e6a683": {
			"file": "apps/mem-claw/src/hooks/openclaw-observe-controller.ts",
			"function": "finalizeObserveSession",
			"line": 170,
			"column": 4,
			"file_hash": "05fb39f3e3a073654c8644589d703f72e7227f30dcc6ad8b7be5eb00609b1bd6"
		},
		"hooks.openclaw-runtime-hooks.contained.memory-hook-skipped": {
			"file": "apps/mem-claw/src/hooks/openclaw-runtime-hooks.ts",
			"function": "contained",
			"line": 19,
			"column": 5,
			"file_hash": "026b9fa0a256d28555dbe5db03e40bd4db7a7a2034031f9ed44b2cc6108cc8d7"
		},
		"hooks.openclaw-runtime-hooks.registerRuntimeHooks.context-degraded": {
			"file": "apps/mem-claw/src/hooks/openclaw-runtime-hooks.ts",
			"function": "registerRuntimeHooks",
			"line": 76,
			"column": 30,
			"file_hash": "026b9fa0a256d28555dbe5db03e40bd4db7a7a2034031f9ed44b2cc6108cc8d7"
		},
		"upgrade.manifest.completed": {
			"file": "apps/mem-claw/src/install/check.ts",
			"function": "fetchManifest",
			"line": 70,
			"column": 3,
			"file_hash": "3b4a309f11f96133d513c06a5baa78aaae71eeaf4140cff8f58a37fcbbce1799"
		},
		"upgrade.check.completed": {
			"file": "apps/mem-claw/src/install/check.ts",
			"function": "scheduleBackgroundUpgrade",
			"line": 95,
			"column": 3,
			"file_hash": "3b4a309f11f96133d513c06a5baa78aaae71eeaf4140cff8f58a37fcbbce1799"
		},
		"upgrade.gc.failed": {
			"file": "apps/mem-claw/src/install/check.ts",
			"function": "scheduleBackgroundUpgrade",
			"line": 109,
			"column": 3,
			"file_hash": "3b4a309f11f96133d513c06a5baa78aaae71eeaf4140cff8f58a37fcbbce1799"
		},
		"conversation-access-policy.ensureConversationAccessGranted.2e15c2b7fb": {
			"file": "apps/mem-claw/src/install/conversation-access-policy.ts",
			"function": "ensureConversationAccessGranted",
			"line": 85,
			"column": 2,
			"file_hash": "6b7145acbd08887b4e6421545bbd3e2eaf67ec096e99da87b9fd713376bcf7d1"
		},
		"plugin.conversation-access-policy.ensureConversationAccessGranted.d508d2f9f8": {
			"file": "apps/mem-claw/src/install/conversation-access-policy.ts",
			"function": "ensureConversationAccessGranted",
			"line": 109,
			"column": 4,
			"file_hash": "6b7145acbd08887b4e6421545bbd3e2eaf67ec096e99da87b9fd713376bcf7d1"
		},
		"upgrade.download.activated": {
			"file": "apps/mem-claw/src/install/download.ts",
			"function": "downloadAndStage",
			"line": 75,
			"column": 2,
			"file_hash": "5f0c2f37471158a03ee73ab2fa737ea89eeb5cfc4f001a560507d3d3d28e741a"
		},
		"upgrade.existing.activated": {
			"file": "apps/mem-claw/src/install/download.ts",
			"function": "activateExistingVersion",
			"line": 100,
			"column": 2,
			"file_hash": "5f0c2f37471158a03ee73ab2fa737ea89eeb5cfc4f001a560507d3d3d28e741a"
		},
		"upgrade.download.cleanup_failed": {
			"file": "apps/mem-claw/src/install/download.ts",
			"function": "downloadAndVerify",
			"line": 122,
			"column": 4,
			"file_hash": "5f0c2f37471158a03ee73ab2fa737ea89eeb5cfc4f001a560507d3d3d28e741a"
		},
		"upgrade.preflight.failed": {
			"file": "apps/mem-claw/src/install/download.ts",
			"function": "preflightExistingVersion",
			"line": 240,
			"column": 3,
			"file_hash": "5f0c2f37471158a03ee73ab2fa737ea89eeb5cfc4f001a560507d3d3d28e741a"
		},
		"upgrade.invalid_stage.quarantine_failed": {
			"file": "apps/mem-claw/src/install/download.ts",
			"function": "quarantineDir",
			"line": 258,
			"column": 3,
			"file_hash": "5f0c2f37471158a03ee73ab2fa737ea89eeb5cfc4f001a560507d3d3d28e741a"
		},
		"upgrade.runtime.quarantine_failed": {
			"file": "apps/mem-claw/src/install/entry-shim.ts",
			"function": "quarantineStagedRuntime",
			"line": 52,
			"column": 4,
			"file_hash": "4365d196f6b3efedef6e918236df9244a4c3d0a5d01f3c58c83704820fc38298"
		},
		"upgrade.background.failed": {
			"file": "apps/mem-claw/src/install/entry-shim.ts",
			"function": "writeBackgroundUpgradeError",
			"line": 78,
			"column": 3,
			"file_hash": "4365d196f6b3efedef6e918236df9244a4c3d0a5d01f3c58c83704820fc38298"
		},
		"upgrade.active_version.read_failed": {
			"file": "apps/mem-claw/src/install/stage.ts",
			"function": "resolveActiveVersion",
			"line": 78,
			"column": 31,
			"file_hash": "4653739cb24517b85b5214c4ec251d34e58345dc6a7b4861f938bee90923ced2"
		},
		"upgrade.obsolete_stage.cleanup_failed": {
			"file": "apps/mem-claw/src/install/stage.ts",
			"function": "resolveActiveVersion",
			"line": 96,
			"column": 4,
			"file_hash": "4653739cb24517b85b5214c4ec251d34e58345dc6a7b4861f938bee90923ced2"
		},
		"upgrade.quarantine.read_failed": {
			"file": "apps/mem-claw/src/install/stage.ts",
			"function": "quarantineActiveVersion",
			"line": 118,
			"column": 31,
			"file_hash": "4653739cb24517b85b5214c4ec251d34e58345dc6a7b4861f938bee90923ced2"
		},
		"upgrade.quarantine.completed": {
			"file": "apps/mem-claw/src/install/stage.ts",
			"function": "quarantineActiveVersion",
			"line": 147,
			"column": 2,
			"file_hash": "4653739cb24517b85b5214c4ec251d34e58345dc6a7b4861f938bee90923ced2"
		},
		"upgrade.gc.link_read_failed": {
			"file": "apps/mem-claw/src/install/stage.ts",
			"function": "runBootGc",
			"line": 172,
			"column": 32,
			"file_hash": "4653739cb24517b85b5214c4ec251d34e58345dc6a7b4861f938bee90923ced2"
		},
		"upgrade.gc.directory_read_failed": {
			"file": "apps/mem-claw/src/install/stage.ts",
			"function": "safeReaddir",
			"line": 231,
			"column": 31,
			"file_hash": "4653739cb24517b85b5214c4ec251d34e58345dc6a7b4861f938bee90923ced2"
		},
		"upgrade.gc.remove_failed": {
			"file": "apps/mem-claw/src/install/stage.ts",
			"function": "safeRm",
			"line": 248,
			"column": 31,
			"file_hash": "4653739cb24517b85b5214c4ec251d34e58345dc6a7b4861f938bee90923ced2"
		},
		"tool.execute.completed": {
			"file": "apps/mem-claw/src/tools/with-tool-observability.ts",
			"function": "wrapTool.execute",
			"line": 118,
			"column": 5,
			"file_hash": "c2eef53c99fb3d24de91668ab6220c162339dd74086b81de370d640deb53b72d"
		}
	}
};
